test_0 (__main__.lab3a)
[Lab 3] - [Investigation 1] - [Part 4] - Functions - Test for file creation: ./lab3a.py ... ok
test_1 (__main__.lab3a)
[Lab 3] - [Investigation 1] - [Part 4] - Functions - Test for errors running: ./lab3a.py ... ok
test_2 (__main__.lab3a)
[Lab 3] - [Investigation 1] - [Part 4] - Functions - Test for correct shebang line: ./lab3a.py ... ok
test_4_function_return_text_value (__main__.lab3a)
[Lab 3] - [Investigation 1] - [Part 4] - Functions - function print_out_text() has correct output ... FAIL

======================================================================
FAIL: test_4_function_return_text_value (__main__.lab3a)
[Lab 3] - [Investigation 1] - [Part 4] - Functions - function print_out_text() has correct output
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kparmar/OPS445/Lab3/./CheckLab3.py", line 79, in test_4_function_return_text_value
    self.assertEqual(lab3aStudent.return_text_value(), expected_output, msg=error_output)
AssertionError: 'Good Morning terry' != 'Good Morning Terry'
- Good Morning terry
?              ^
+ Good Morning Terry
?              ^
 : lab3a.py print_out_text() has wrong output (HINT: make sure you copied the script exactly!

----------------------------------------------------------------------
Ran 4 tests in 0.015s

FAILED (failures=1)
OPS445 Lab Report - System Information for running ./CheckLab3.py
=================================================================
    User login name: kparmar
    Linux system name: kparmar-VirtualBox
    Python executable: /usr/bin/python3
    Python version: 31012
    OS Platform: linux
    Working Directory: /home/kparmar/OPS445/Lab3
    Start at: Mon Sep 30 14:17:10 2024
=================================================================
Good Morning terry
my number is  15
my number is  15
my number is  15
